language: ruby
rvm:
- 2.3
env:
  global:
  - MD_IGNORE="R1"
  - RUBOCOP_OPTS="--fail-level=error"
  - TEST_ROLE_PATH=$PWD
  - secure: gex+loJR9Vrsj71SacTttTt5iKhp8Nhzmt7JnaThZ8TxDFA09+0ru22bi8l7G2I5UV3oEG/mIc/6bm7MhO3027YbCVhK9L7pOPqsjuXkAFhom88v5K5fFFjGtJSvuoPdQQbMcWPpUADyNvJV78fovxmom1bt4I4lXiqErh1cFUByMVxysnUPT1Xm5XNoP6K3jFvYCszw/pOcH0L2UfZGCNPB/Gqbzw6SPWCCXYvfYZ4pt35ioI6Jd8A9rSTqnvMgexm9aImXlFhkm384XzQBpJCBMUAbZVRXoWfYTHSDCk8Z1XpWdItUdkFz1jTlnTE/FPgIzTYQiNZIFUT5bsoSV/S4p/ojeAT0QSuJm0rFKgYfO/LeWlYCax7N/Jq96yDZSF3Hjf1eim6+nxSa4w4sHIxpB1ehTHki6gJIrRhBXsOVhNNti4dndjn1XJ7nLWF/fA7ZamX7fTksazyH8HgQ0bsQPTtJpNI/EMfNiPiYYWO16PUZn9J2KML42kRePkcRbx2EjJvg/WFoalN2hM6KINcjsHl6Nw4lrz25Jp05sdubDCQ1ia1rXocMHE9qg72GlNL1C5Hgb7RWNweL9jW5WGG5IaAwI5mpHemHugEXoNs9R2Q2pYwZ8qEUWdtx+P/imFXgp6cxTaFg9DFQZweV75y13radUJxOJLrhxskgB+w=
addons:
  apt:
    packages:
    - ruby-full
before_install: 
install:
- bundle
before_script: 
script:
- rake
after_success: 
after_failure: 
before_deploy: 
deploy: 
after_deploy: 
after_script: 
notifications:
  slack:
    secure: pm7JCjENEPE6ASWOG/FWsYj8I1tD8+987b+erXljmtZlhYz1Fp2gjSOanmdkFSUIcjqj/JlsUq5MgaAv8QF1PwZO/zdPmv0AvvI+L4XaiEEYOCMgnAmMaHfPwu4WdPHQX0XMKctgubWfg0MmMQ2bZabCUzoimLtRllujn3OvDE5wnBQoUaQai80SiA0l0/Jp4s7YEd33+zrYiY+mulAB5dyaFGyO7Rvub6XF2Rjd8bwT5r692cE+OvTIFPMVBy2rdVgiARcHJ0Dts8dwOZl/Dqx+wq3JnVxRHSPl7GEcu1vVuJ3FlWgcpYnIRn2k5PVFVIdiSL345hptSFRCRJDoKKnM12XzAqP1gLA1RbTafV0J8TNE1T1EsZ3qOcbc5GzMAeD/8P895VQ7Oaur0bPzQ0Zqvj+slRqSiUl2uAnpZRFluHJo2qkbqx3pCqvCm++acghp7QHIZfzKRtG9USzXaQ/PRbnbYkHTFfANQtnWURDp0htLQNLkrZARQ8PlTuMTfbVCsfn9SnR0m0m7xuahDCgBaQcAcjlR7A8qAgqgdLMvBPbreWIyI54HoXe2KcJC78xK0lfRUmImlXp5Ib+DMsRXiwYkMhisgdY8RzXMjP1U8OgyCo0FsA9UpQc4iOC+a+9+6YkTwGYfQYZB5ew7TVxu6dWnwEzlhvy3gLpDD9M=
