language: ruby
rvm:
- 2.3
env:
  global:
  - MD_IGNORE="R1"
  - RUBOCOP_OPTS="--fail-level=error"
  - TEST_ROLE_PATH=$PWD
  - secure: wefL0lPkBX8KEgAaWMhZWifuJoFaJSopMKjuu9jVZJ0W9PgOTUSjsOqHLcgwaWNtnlw/FL/mdAtCjxr8wtl6G0PrXe57Gnao9CBAq7GngUjSXokTSlv83Ka4jsBGFYOE5SM/3/uIL25cr60WsXJhKc2nqUBReM+U05qLlTpJIkoJ4g0BPDvHaypGA/4WB1WZLNEUc3MxMz76O2vsTX+1sjqlLA6PMSe4GfRCHotNKRuVthlF1HVSpE7PsVRirAsa5oVtKMh336mkjr+frk4eCsPYZIrxCwKo/0Qw/5KsBRWPwSdJFblrShAYIEOSEglfzxNvXEtc8HPGO6LNn9b+x/EHX5ngqyJbbw/8WotKW5afNjmxgYZGXMgXFAZF1DhbFf+rAWHOouk0eO13l/k4tdZNI1ea7MsNfrFSTRY4U3BZKMDGk/moAYtk+9Lx0txd2/G1G6VCrfoQ2ByEm7LL0ImuPEHINIRu/7aXvd4XheJIsclVhsVagytHgnw9zHn0t4ak9X4/gE+Qn78DLN2ORZytZl7dIjJSI4BVJvxb8m7sjyopFARUo2iKmOqo1+jHlwdrl4vvk6GzdH6OHfd0CAAmvCPs8Pi0f6jaR37XqipOrEY9OupoHCrpzfg5s4njs2U0ttVXgLRSc9feJ24QSsBKwUrpUf+EPTt9jt0mMEM=
addons:
  apt:
    packages:
    - ruby-full
before_install:
install:
- bundle
before_script:
script:
- rake
after_success:
after_failure:
before_deploy: 
deploy:
after_deploy:
after_script:
notifications:
  slack:
    secure: pm7JCjENEPE6ASWOG/FWsYj8I1tD8+987b+erXljmtZlhYz1Fp2gjSOanmdkFSUIcjqj/JlsUq5MgaAv8QF1PwZO/zdPmv0AvvI+L4XaiEEYOCMgnAmMaHfPwu4WdPHQX0XMKctgubWfg0MmMQ2bZabCUzoimLtRllujn3OvDE5wnBQoUaQai80SiA0l0/Jp4s7YEd33+zrYiY+mulAB5dyaFGyO7Rvub6XF2Rjd8bwT5r692cE+OvTIFPMVBy2rdVgiARcHJ0Dts8dwOZl/Dqx+wq3JnVxRHSPl7GEcu1vVuJ3FlWgcpYnIRn2k5PVFVIdiSL345hptSFRCRJDoKKnM12XzAqP1gLA1RbTafV0J8TNE1T1EsZ3qOcbc5GzMAeD/8P895VQ7Oaur0bPzQ0Zqvj+slRqSiUl2uAnpZRFluHJo2qkbqx3pCqvCm++acghp7QHIZfzKRtG9USzXaQ/PRbnbYkHTFfANQtnWURDp0htLQNLkrZARQ8PlTuMTfbVCsfn9SnR0m0m7xuahDCgBaQcAcjlR7A8qAgqgdLMvBPbreWIyI54HoXe2KcJC78xK0lfRUmImlXp5Ib+DMsRXiwYkMhisgdY8RzXMjP1U8OgyCo0FsA9UpQc4iOC+a+9+6YkTwGYfQYZB5ew7TVxu6dWnwEzlhvy3gLpDD9M=
